# Generated by Django 4.1.4 on 2023-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('username', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='username')),
                ('nick_name', models.CharField(blank=True, max_length=30, verbose_name='nick name ')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='phone number')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='sex')),
                ('country', models.CharField(choices=[('GA', 'Gabon'), ('TR', 'Türkiye'), ('FR', 'France')], default='GA', max_length=50, verbose_name='country')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='joined date ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
